In [1]:
import os
import streamlit as st
import pickle
import time
import langchain
from langchain import OpenAI
from langchain.chains import RetrievalQAWithSourcesChain
from langchain.chains.qa_with_sources.loading import load_qa_with_sources_chain
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.document_loaders import UnstructuredURLLoader
from langchain.embeddings import OpenAIEmbeddings
from langchain.vectorstores import FAISS
from langchain.document_loaders import TextLoader
from langchain.document_loaders.csv_loader import CSVLoader

DOCUMENT LOADING

An array with 0th element consists of whole page content.

The other elements are meta data of the text file.

In [2]:
loader= TextLoader('nvda_news_1.txt')
data=loader.load()
data

[Document(page_content="The stock of NVIDIA Corp (NASDAQ:NVDA) experienced a daily loss of -3.56% and a 3-month gain of 32.35%. With an Earnings Per Share (EPS) (EPS) of $1.92, the question arises: is the stock significantly overvalued? This article aims to provide a detailed valuation analysis of NVIDIA, offering insights into its financial strength, profitability, growth, and more. We invite you to delve into this comprehensive analysis.\n\nCompany Overview\nWarning! GuruFocus has detected 10 Warning Signs with NVDA. Click here to check it out.\n\nNVDA 30-Year Financial Data\n\nThe intrinsic value of NVDA\n\n\nNVIDIA Corp (NASDAQ:NVDA) is a leading designer of discrete graphics processing units that enhance the experience on computing platforms. The firm's chips are widely used in various end markets, including PC gaming and data centers. In recent years, NVIDIA has broadened its focus from traditional PC graphics applications such as gaming to more complex and favorable opportunitie

In [3]:
loader= CSVLoader('movies.csv',source_column='title')
data_mov=loader.load()
data_mov

[Document(page_content='movie_id: 101\ntitle: K.G.F: Chapter 2\nindustry: Bollywood\nrelease_year: 2022\nimdb_rating: 8.4\nstudio: Hombale Films\nlanguage_id: 3\nbudget: 1\nrevenue: 12.5\nunit: Billions\ncurrency: INR', metadata={'source': 'K.G.F: Chapter 2', 'row': 0}),
 Document(page_content='movie_id: 102\ntitle: Doctor Strange in the Multiverse of Madness\nindustry: Hollywood\nrelease_year: 2022\nimdb_rating: 7\nstudio: Marvel Studios\nlanguage_id: 5\nbudget: 200\nrevenue: 954.8\nunit: Millions\ncurrency: USD', metadata={'source': 'Doctor Strange in the Multiverse of Madness', 'row': 1}),
 Document(page_content='movie_id: 103\ntitle: Thor: The Dark World\nindustry: Hollywood\nrelease_year: 2013\nimdb_rating: 6.8\nstudio: Marvel Studios\nlanguage_id: 5\nbudget: 165\nrevenue: 644.8\nunit: Millions\ncurrency: USD', metadata={'source': 'Thor: The Dark World', 'row': 2}),
 Document(page_content='movie_id: 104\ntitle: Thor: Ragnarok\nindustry: Hollywood\nrelease_year: 2017\nimdb_rating: 

In [4]:
loader=UnstructuredURLLoader(urls=[
    "https://www.moneycontrol.com/news/business/banks/hdfc-bank-re-appoints-sanmoy-chakrabarti-as-chief-risk-officer-11259771.html",
        "https://www.moneycontrol.com/news/business/markets/market-corrects-post-rbi-ups-inflation-forecast-icrr-bet-on-these-top-10-rate-sensitive-stocks-ideas-11142611.html"
    ])

In [5]:
data=loader.load()
len(data)

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\akhil\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger.zip.


2

In [7]:
data[0].metadata

{'source': 'https://www.moneycontrol.com/news/business/banks/hdfc-bank-re-appoints-sanmoy-chakrabarti-as-chief-risk-officer-11259771.html'}

TEXT SPLITTING

In [8]:
text="""Interstellar is a 2014 epic science fiction film co-written, directed, and produced by Christopher Nolan. It stars Matthew McConaughey, Anne Hathaway, Jessica Chastain, Bill Irwin, Ellen Burstyn, Michael Caine, and Matt Damon. Set in a dystopian future where humanity is embroiled in a catastrophic blight and famine, the film follows a group of astronauts who travel through a wormhole near Saturn in search of a new home for humankind.

Brothers Christopher and Jonathan Nolan wrote the screenplay, which had its origins in a script Jonathan developed in 2007 and was originally set to be directed by Steven Spielberg. Kip Thorne, a Caltech theoretical physicist and 2017 Nobel laureate in Physics,[4] was an executive producer, acted as a scientific consultant, and wrote a tie-in book, The Science of Interstellar. Cinematographer Hoyte van Hoytema shot it on 35 mm movie film in the Panavision anamorphic format and IMAX 70 mm. Principal photography began in late 2013 and took place in Alberta, Iceland, and Los Angeles. Interstellar uses extensive practical and miniature effects, and the company Double Negative created additional digital effects.

Interstellar premiered in Los Angeles on October 26, 2014. In the United States, it was first released on film stock, expanding to venues using digital projectors. The film received positive reviews from critics and grossed over $681 million worldwide ($703 million after subsequent re-releases), making it the tenth-highest-grossing film of 2014. It has been praised by astronomers for its scientific accuracy and portrayal of theoretical astrophysics.[5][6][7] Interstellar was nominated for five awards at the 87th Academy Awards, winning Best Visual Effects, and received numerous other accolades."""

In [9]:
from langchain.text_splitter import CharacterTextSplitter

In [16]:
r_splitter=RecursiveCharacterTextSplitter(
    separators=["\n\n","\n"," "],
    chunk_size = 200,
    chunk_overlap=0
)

chunks=r_splitter.split_text(text)
len(chunks)

11

RecursiveCharacterTextSplitter splits once each for splitter one after another.

In [17]:
for chunk in  chunks:
    print(len(chunk))

195
195
45
195
199
191
128
198
191
199
10


Vector Database - FAISS

Each chunk will be converted into embeddings

The question asked by user is also converted into embeddings

FAISS will check for the similar embeddings from the text and the question and give output of those similar ones.

In [18]:
pip install faiss-cpu

                                              0.0/14.5 MB ? eta -:--:--
                                              0.0/14.5 MB ? eta -:--:--
                                             0.1/14.5 MB 648.1 kB/s eta 0:00:23
                                             0.1/14.5 MB 930.9 kB/s eta 0:00:16
                                              0.2/14.5 MB 1.2 MB/s eta 0:00:12
                                              0.2/14.5 MB 1.2 MB/s eta 0:00:12
     -                                        0.5/14.5 MB 1.8 MB/s eta 0:00:08
     -                                        0.5/14.5 MB 1.6 MB/s eta 0:00:09
     --                                       0.8/14.5 MB 2.0 MB/s eta 0:00:07
     --                                       1.0/14.5 MB 2.2 MB/s eta 0:00:07
     ---                                      1.2/14.5 MB 2.5 MB/s eta 0:00:06
     ---                                      1.4/14.5 MB 2.6 MB/s eta 0:00:06
     ----                                     1.7/14.5 MB 2.9 MB


[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [19]:
pip install sentence-transformers


                                              0.0/156.5 kB ? eta -:--:--
     --                                       10.2/156.5 kB ? eta -:--:--
     -------                               30.7/156.5 kB 330.3 kB/s eta 0:00:01
     -------------------                   81.9/156.5 kB 573.4 kB/s eta 0:00:01
     -------------------                   81.9/156.5 kB 573.4 kB/s eta 0:00:01
     ------------------------------------ 156.5/156.5 kB 720.4 kB/s eta 0:00:00
                                              0.0/8.5 MB ? eta -:--:--
                                              0.2/8.5 MB 5.1 MB/s eta 0:00:02
                                              0.2/8.5 MB 5.4 MB/s eta 0:00:02
     --                                       0.5/8.5 MB 3.5 MB/s eta 0:00:03
     --                                       0.5/8.5 MB 3.5 MB/s eta 0:00:03
     ----                                     0.9/8.5 MB 4.0 MB/s eta 0:00:02
     ----                                     1.0/8.5 MB 4.4 MB/s eta 0

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [21]:
import pandas as pd

In [22]:
df=pd.read_csv('sample_text.csv')
df

text category
0      Meditation and yoga can improve mental health   Health
1  Fruits, whole grains and vegetables helps cont...   Health
2  These are the latest fashion trends for this week  Fashion
3  Vibrant color jeans for male are becoming a trend  Fashion
4                 The concert starts at 7 PM tonight    Event
5  Navaratri dandiya program at Expo center in Mu...    Event
6  Exciting vacation destinations for your next trip   Travel
7  Maldives and Srilanka are gaining popularity i...   Travel

In [23]:
from sentence_transformers import SentenceTransformer

This is used to transform text into vectors

In [24]:
encoder=SentenceTransformer("all-mpnet-base-v2")
vectors=encoder.encode(df.text)
vectors.shape

c:\Users\akhil\AppData\Local\Programs\Python\Python311\Lib\site-packages\huggingface_hub\file_download.py:149: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\akhil\.cache\huggingface\hub\models--sentence-transformers--all-mpnet-base-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


(8, 768)

In [25]:
vectors

array([[-0.00247395,  0.03626723, -0.05290459, ..., -0.09152358,
        -0.03969997, -0.04330491],
       [-0.03357265,  0.00980516, -0.0325013 , ..., -0.05165467,
         0.02245887, -0.03156184],
       [-0.0186532 , -0.04051321, -0.01235388, ...,  0.00610587,
        -0.07179647,  0.02773852],
       ...,
       [-0.00066458,  0.04252128, -0.05645507, ...,  0.01315469,
        -0.03183567, -0.04357662],
       [-0.03317154,  0.03252459, -0.0248484 , ...,  0.01174422,
         0.05747123,  0.00571021],
       [-0.00166393,  0.00413826, -0.04597082, ...,  0.02008527,
         0.05656241, -0.00161597]], dtype=float32)

In [26]:
dim=vectors.shape[1]
dim

768

In [27]:
import faiss
index=faiss.IndexFlatL2(dim)
index

<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x000001FDA5999230> >

In [28]:
index.add(vectors)

In [29]:
search_query="I want to buy a polo t-shirt"
vec=encoder.encode(search_query)
vec.shape

(768,)

In [31]:
import numpy as np

In [32]:
svec=np.array(vec).reshape(1,-1)
svec.shape

(1, 768)

In [34]:
distances, I = index.search(svec,k=2)

In [35]:
distances

array([[1.3844836, 1.4039094]], dtype=float32)

In [36]:
I

array([[3, 2]], dtype=int64)

First list is the distances 
Second list is the indexes in the original dataframe

In [37]:
df.loc[I[0]]

text category
3  Vibrant color jeans for male are becoming a trend  Fashion
2  These are the latest fashion trends for this week  Fashion

In [38]:
search_query

'I want to buy a polo t-shirt'

In [39]:
os.environ['OPEN_API_KEY']='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'

In [ ]:
llm=OpenAI(temperature=0.9,max_tokens=500)